### ISSUE TITLE
App crashes when dragging a file over it

### ISSUE THREAD

**Issue by pioul** [bufferapp/buffer-publish#206] opened 2017-10-30 14:20 UTC
Dragging a file over the dashboard makes the app crash. Being able to drag a file over it is important for some drag & drop upload features inside the composer.

Screencast: http://hi.buffer.com/nOEM

I'm running Chrome stable 62.0.3202.75

Stack traces:

```
warning.js?00c0:33 Warning: Failed prop type: The prop `profileId` is marked as required in `PostDragWrapper`, but its value is `undefined`.
    in PostDragWrapper (created by DragSource(PostDragWrapper))
    in DragSource(PostDragWrapper) (created by DropTarget(DragSource(PostDragWrapper)))
    in DropTarget(DragSource(PostDragWrapper)) (created by QueueItems)
    in div (created by QueueItems)
    in div (created by QueueItems)
    in QueueItems (created by QueuedPosts)
    in div (created by QueuedPosts)
    in QueuedPosts (created by Connect(QueuedPosts))
    in Connect(QueuedPosts) (created by ProfilePage)
    in div (created by ScrollableContainer)
    in ScrollableContainer (created by ProfilePage)
    in div (created by ProfilePage)
    in div (created by ProfilePage)
    in ProfilePage (created by Connect(ProfilePage))
    in Connect(ProfilePage) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by DragDropContext(App))
    in DragDropContext(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
    in AppContainer

---

warning.js?00c0:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `PostDragLayer`.
    in PostDragLayer (created by DragLayer(PostDragLayer))
    in DragLayer(PostDragLayer) (created by QueuedPosts)
    in div (created by QueuedPosts)
    in QueuedPosts (created by Connect(QueuedPosts))
    in Connect(QueuedPosts) (created by ProfilePage)
    in div (created by ScrollableContainer)
    in ScrollableContainer (created by ProfilePage)
    in div (created by ProfilePage)
    in div (created by ProfilePage)
    in ProfilePage (created by Connect(ProfilePage))
    in Connect(ProfilePage) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by DragDropContext(App))
    in DragDropContext(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
    in AppContainer

---

invariant.js?085f:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `PostDragLayer`.
    at invariant (eval at <anonymous> (bundle.js:779), <anonymous>:42:15)
    at createFiberFromElementType (eval at <anonymous> (bundle.js:12759), <anonymous>:8185:5)
    at createFiberFromElement (eval at <anonymous> (bundle.js:12759), <anonymous>:8130:15)
    at reconcileSingleElement (eval at <anonymous> (bundle.js:12759), <anonymous>:9378:19)
    at reconcileChildFibers (eval at <anonymous> (bundle.js:12759), <anonymous>:9477:35)
    at reconcileChildrenAtPriority (eval at <anonymous> (bundle.js:12759), <anonymous>:10127:30)
    at reconcileChildren (eval at <anonymous> (bundle.js:12759), <anonymous>:10118:5)
    at updateHostComponent (eval at <anonymous> (bundle.js:12759), <anonymous>:10370:5)
    at beginWork (eval at <anonymous> (bundle.js:12759), <anonymous>:10609:16)
    at performUnitOfWork (eval at <anonymous> (bundle.js:12759), <anonymous>:12573:16)

---

react-dom.development.js?7bc3:8305 The above error occurred in the <div> component:
    in div (created by PostDragLayer)
    in div (created by PostDragLayer)
    in PostDragLayer (created by DragLayer(PostDragLayer))
    in DragLayer(PostDragLayer) (created by QueuedPosts)
    in div (created by QueuedPosts)
    in QueuedPosts (created by Connect(QueuedPosts))
    in Connect(QueuedPosts) (created by ProfilePage)
    in div (created by ScrollableContainer)
    in ScrollableContainer (created by ProfilePage)
    in div (created by ProfilePage)
    in div (created by ProfilePage)
    in ProfilePage (created by Connect(ProfilePage))
    in Connect(ProfilePage) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by DragDropContext(App))
    in DragDropContext(App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
    in AppContainer

Consider adding an error boundary to your tree to customize error handling behavior.
You can learn more about error boundaries at https://fb.me/react-error-boundaries.

---

react-dom.development.js?7bc3:1345 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (eval at <anonymous> (bundle.js:12759), <anonymous>:1345:19)
    at invokeGuardedCallback (eval at <anonymous> (bundle.js:12759), <anonymous>:1195:27)
    at performWork (eval at <anonymous> (bundle.js:12759), <anonymous>:12800:7)
    at scheduleUpdateImpl (eval at <anonymous> (bundle.js:12759), <anonymous>:13185:19)
    at scheduleUpdate (eval at <anonymous> (bundle.js:12759), <anonymous>:13124:12)
    at Object.enqueueSetState (eval at <anonymous> (bundle.js:12759), <anonymous>:9646:7)
    at DragLayerContainer.ReactComponent.setState (eval at <anonymous> (bundle.js:13388), <anonymous>:218:16)
    at DragLayerContainer.handleChange (eval at <anonymous> (bundle.js:12661), <anonymous>:128:18)
    at handleChange (eval at <anonymous> (bundle.js:10788), <anonymous>:84:5)
    at dispatch (eval at <anonymous> (bundle.js:10865), <anonymous>:186:7)
```

**Comment by hamstu** [comment] 2017-10-31 21:52
Thanks for reporting this one @pioul and @emily-plummer. I've found the cause, and it'll be fixed with my next PR! 😄  (https://github.com/bufferapp/buffer-publish/pull/201)

**Comment by hamstu** [comment] 2017-11-30 22:52
This is fixed!

**Closed by hamstu** 2017-11-30 22:52 UTC
Labels: bug
